### ISSUE TITLE
BUG: List of Hydras Not Updating

### ISSUE THREAD

**Issue by chriswmackey** [HydraShare/hydra#29] opened 2016-01-29 16:24 UTC
A few hours ago, all of my recent THERM example files were appearing on the Hydra main display pageand now they are all gone:
https://hydrashare.github.io/hydra/index.html

The examples are still on my fork and they can still appear in their own viewer pages as you can see this THERM one here:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Analyze_THERM_Results&slide=0&scale=1&offset=0,0
So the issue is only with the main page.  Specifically, the request to the google macro is not working correctly:
https://script.google.com/macros/s/AKfycbxiRnl-119Qy-Ygchrjp5OiMelYUJCZ-ZHjpwKTm6dtaYCOZ9IZ/exec

https://github.com/HydraShare/hydra/blob/gh-pages/lib/hydra.js#L31-L35

**Comment by mostaphaRoudsari** [comment] 2016-01-30 14:31
@chriswmackey I checked this. The issue is not from us but the github API. The API call doesn't return your fork as one of the forks: https://api.github.com/repos/HydraShare/Hydra/forks (it returns 30 forks)

However you show up here in members: https://github.com/HydraShare/hydra/network/members (32 members)

I'll test again early next week and let you know if I found a better solution.

The google script works fine:
![image](https://cloud.githubusercontent.com/assets/2915573/12696270/fd5ae2c4-c733-11e5-9b47-a37efe293232.png)

**Comment by chriswmackey** [comment] 2016-01-31 02:40
@mostaphaRoudsari ,
In this case, can we change the link given to the THERM example files on the [release notes](http://www.grasshopper3d.com/group/ladybug/forum/topics/release-notes-ladybug-0-0-62-and-honeybee-0-0-59) to list out each individual file?
So this:
https://hydrashare.github.io/hydra/index.html?keywords=LBNL

Will change to this:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=THERM_Export_Workflow
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=THERM_Comparison_of_Stud_Wall_Constructions
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Analyze_THERM_Results
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Thermal_Bridging_with_THERM_and_EnergyPlus
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=THERM_Window_Frame_Construction
https://github.com/chriswmackey/hydra_2/tree/master/Import_Glazing_System_from_LBNL_WINDOW
https://github.com/chriswmackey/hydra_2/tree/master/Import_LBNL_WINDOW_Glazing_Assembly_for_EnergyPlus
Otherwise, no one will be able to find the new THERM example files.

Also, if what you say is the case, why are some of my old example files like the wind profile component showing up on the main page?
-Chris

**Comment by mostaphaRoudsari** [comment] 2016-01-31 14:35
@chriswmackey thanks. I changed the links. It's because Hydra caches the list of example files. The newer one has been overwritten but the old ones are there. Let me check again and see if I can find a better solution.

**Comment by mostaphaRoudsari** [comment] 2016-01-31 14:46
ok. I was right and wrong. It's a bug but in a good way! Now that the number of forks has exceeded one page, the very first forks shows up on page 2 which we can get it by: https://api.github.com/repos/HydraShare/Hydra/forks?page=2

**Comment by mostaphaRoudsari** [comment] 2016-01-31 15:38
I fixed this in code however I exceeded Github's API rate limit. It should be fixed in couple of hours once the limitation is over.

**Comment by mostaphaRoudsari** [comment] 2016-01-31 16:57
![image](https://cloud.githubusercontent.com/assets/2915573/12703459/da9acba8-c811-11e5-92ca-708539e380ab.png)

**Closed as completed by mostaphaRoudsari** 2016-01-31 16:57 UTC
Labels: bug, Critical
